version: '3'

services:
  django: &django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /app/
    ports:
      - "8000:8000"
    depends_on:
      - broker
      - worker

  broker:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"


  worker:
    build: .
    command: celery -A eMenu.celery worker --loglevel=INFO
    depends_on:
      - broker

  scheduler:
    build: .
    command: celery -A eMenu beat -l info
    depends_on:
      - broker
      - worker
