# Generated by Django 3.1 on 2020-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('prepare_time', models.TimeField()),
                ('is_vege', models.BooleanField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('dishes', models.ManyToManyField(to='menu.Dish')),
            ],
        ),
    ]
