# Generated by Django 3.1 on 2020-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='prepare_time',
            field=models.IntegerField(),
        ),
    ]
