# Generated by Django 3.1 on 2020-08-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dascription',
            new_name='description',
        ),
    ]
