# Generated by Django 3.1 on 2020-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200831_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='prepare_time',
            new_name='preparation_time',
        ),
        migrations.AlterField(
            model_name='dish',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
