# Generated by Django 3.1 on 2020-08-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200831_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='menu.Dish'),
        ),
    ]
