# Generated by Django 3.1 on 2020-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200831_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_vege',
            field=models.BooleanField(verbose_name='Danie wegetariańskie'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.TextField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Zdjęcie dania'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation_time',
            field=models.IntegerField(verbose_name='Czas przygotowania'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='menu.Dish', verbose_name='Dania'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowano'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
    ]
