# Generated by Django 3.1 on 2020-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200905_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Zdjęcie dania'),
        ),
    ]
