# Generated by Django 3.1 on 2020-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200905_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.FileField(upload_to='', verbose_name='Zdjęcie dania'),
        ),
    ]
