# Generated by Django 3.1 on 2020-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200905_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Zdjęcie dania'),
        ),
    ]
