# Generated by Django 3.1 on 2020-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200905_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Zdjęcie dania'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menu.Dish', verbose_name='Dania'),
        ),
    ]
