# Generated by Django 3.1 on 2020-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200906_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishes_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
