# Generated by Django 3.1 on 2020-09-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menu_dishes_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dishes_length',
        ),
    ]
