# Generated by Django 3.1 on 2020-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_menu_dishes_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
