# Generated by Django 3.1 on 2020-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_menu_dishes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dishes_count',
        ),
        migrations.AddField(
            model_name='menu',
            name='dishes_length',
            field=models.IntegerField(default=0),
        ),
    ]
