# Generated by Django 3.1 on 2020-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20200906_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dishes_length',
        ),
        migrations.AddField(
            model_name='menu',
            name='dishes_count',
            field=models.IntegerField(default=0, verbose_name='Liczba dań w karcie'),
        ),
    ]
