# Generated by Django 3.1 on 2020-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20200906_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='menu.Dish', verbose_name='Dania'),
        ),
    ]
