# Generated by Django 3.1 on 2020-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20200906_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dishes_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Liczba dań w karcie'),
        ),
    ]
